FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Копирование requirements и установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Создание структуры директорий
RUN mkdir -p courses/management/commands

# Копирование остальных файлов проекта
COPY . .

# Убедимся, что файлы __init__.py существуют
RUN touch courses/management/__init__.py
RUN touch courses/management/commands/__init__.py

# Создание пользователя и назначение прав
RUN useradd -m myuser
RUN chown -R myuser:myuser /app
USER myuser

EXPOSE 8000

CMD ["sh", "-c", "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
