version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        echo 'Database is ready!'
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=learning_platform.settings
      - POSTGRES_DB=learning_platform
      - POSTGRES_USER=learning_platform_user
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_HOST=db
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=learning_platform
      - POSTGRES_USER=learning_platform_user
      - POSTGRES_PASSWORD=your_secure_password

volumes:
  postgres_data:

