# Generated by Django 4.2.17 on 2025-01-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="topicrating", name="comment",),
    ]
